/**
 * TypeTorch runtime kit: Reflect.
 *
 * The metadata store that code generated by `@typetorch/transformer` writes into. Copy this folder into
 * `@typetorch/framework` (`src/reflection/`) and export it from the package root. The framework ships inside every
 * artifact, so each generation requires its own copy of this module and starts with an empty store.
 *
 * Generated code (decorated classes):
 * ```lua
 * Reflect.defineMetadata(ShopService, "identifier", "server/services/shop@ShopService")
 * Reflect.defineMetadata(ShopService, "typetorch:parameters", { "server/services/data@DataService" })
 * Reflect.decorate(ShopService, "@typetorch/framework:decorators@Service", Service, {})
 * ```
 *
 * Adapted from Flamework's Reflect (MIT, Copyright (c) 2021 Flamework).
 */
import type { AbstractConstructor, ClassDescriptor, MethodDescriptor, PropertyDescriptor } from "./modding";

export namespace Reflect {
	/** object -> property -> key -> value */
	const metadata = new WeakMap<object, Map<string | typeof NO_PROP_MARKER, Map<string, unknown>>>();

	/** Decorated objects by decorator id, in decoration order (class decorators only). */
	export const decorators = new Map<string, Array<AbstractConstructor>>();

	/** Every object registered with an `identifier`, by id. Dependency ids resolve through this. */
	export const idToObj = new Map<string, object>();

	/** The reverse of {@link idToObj}. */
	export const objToId = new Map<object, string>();

	const NO_PROP_MARKER = {} as { _nominal_Marker: never };

	function getObjMetadata(obj: object, prop: string | undefined, create: true): Map<string, unknown>;
	function getObjMetadata(obj: object, prop?: string): Map<string, unknown> | undefined;
	function getObjMetadata(obj: object, prop?: string, create?: boolean) {
		const realProp = prop ?? NO_PROP_MARKER;
		if (create) {
			let objMetadata = metadata.get(obj);
			if (!objMetadata) metadata.set(obj, (objMetadata = new Map()));

			let propMetadata = objMetadata.get(realProp);
			if (!propMetadata) objMetadata.set(realProp, (propMetadata = new Map()));

			return propMetadata;
		} else {
			return metadata.get(obj)?.get(realProp);
		}
	}

	/** The superclass of a roblox-ts class (its metatable's `__index`). */
	function getParentConstructor(obj: object) {
		const metatable = getmetatable(obj) as { __index?: object };
		if (metatable && typeIs(metatable, "table")) {
			return rawget(metatable, "__index") as object | undefined;
		}
	}

	/**
	 * Apply metadata onto this object.
	 *
	 * The `identifier` key is special: its value is a unique id that registers the object in {@link idToObj}.
	 */
	export function defineMetadata(obj: object, key: string, value: unknown, property?: string) {
		if (key === "identifier") {
			assert(typeIs(value, "string"), "identifier must be a string.");
			assert(!objToId.has(obj), `${obj} is already registered.`);
			assert(!idToObj.has(value), `id ${value} is already registered.`);

			objToId.set(obj, value);
			idToObj.set(value, obj);
		}

		getObjMetadata(obj, property, true).set(key, value);
	}

	/**
	 * Get metadata from this object.
	 * Type parameter is an assertion.
	 */
	export function getOwnMetadata<T>(obj: object, key: string, property?: string): T | undefined {
		return getObjMetadata(obj, property)?.get(key) as T | undefined;
	}

	/**
	 * Check if this object has the specified metadata key.
	 */
	export function hasOwnMetadata(obj: object, key: string, property?: string) {
		return getObjMetadata(obj, property)?.has(key) ?? false;
	}

	/**
	 * Get metadata from this object or its parents.
	 * Type parameter is an assertion.
	 */
	export function getMetadata<T>(obj: object, key: string, property?: string): T | undefined {
		const value = getOwnMetadata<T>(obj, key, property);
		if (value !== undefined) {
			return value;
		}

		const parent = getParentConstructor(obj);
		if (parent) {
			return getMetadata<T>(parent, key, property);
		}
	}

	/**
	 * Retrieve all values for the specified key from the object and its parents (own value first).
	 * Type parameter is an assertion.
	 */
	export function getMetadatas<T extends defined>(obj: object, key: string, property?: string): T[] {
		const values = new Array<T>();

		const value = getOwnMetadata<T>(obj, key, property);
		if (value !== undefined) {
			values.push(value);
		}

		const parent = getParentConstructor(obj);
		if (parent) {
			for (const parentValue of getMetadatas<T>(parent, key, property)) {
				values.push(parentValue);
			}
		}

		return values;
	}

	/** The id an object was registered with (`identifier` metadata), if any. */
	export function getIdFromObject(obj: object): string | undefined {
		return objToId.get(obj);
	}

	/** The object registered with this id (`identifier` metadata), if any. */
	export function getObjectFromId(id: string): object | undefined {
		return idToObj.get(id);
	}

	/**
	 * Runs a decorator made with `Modding.createDecorator` / `createMetaDecorator`. Only generated code calls this.
	 *
	 * @hidden
	 */
	export function decorate<A extends readonly unknown[]>(
		object: AbstractConstructor,
		id: string,
		rawDecoration: { _typetorch_parameters: [...A] },
		args: [...A],
		property?: string,
		isStatic = false,
	) {
		const decoration = rawDecoration as unknown as {
			func: (descriptor: ClassDescriptor | MethodDescriptor | PropertyDescriptor, config: [...A]) => void;
		};

		const descriptor = {
			id,
			isStatic,
			object,
			constructor: "new" in object ? object : undefined,
			property,
		};

		if (property === undefined) {
			let decoratedObjects = decorators.get(id);
			if (!decoratedObjects) decorators.set(id, (decoratedObjects = []));

			decoratedObjects.push(object);
		}

		decoration.func(descriptor as never, args);
	}
}
